### ISSUE TITLE
Add a light switch for the parking assist laser

### ISSUE THREAD

**Issue by dkerr64** [ratgdo/homekit-ratgdo32#23]
Currently parking assist laser is coded to come on for 60 seconds when arriving vehicle arrives.

However, I am finding that the vehicle presence (and therefor arrival/departure) sensing is very inconsistent.

So, should we add a light switch accessory to HomeKit (and a button on the device web page) to allow manual control of the laser... and of course, inclusion in HomeKit automations?

**Comment by PaulWieland** [comment]
I have a manual switch in esphome which is helpful during initial setup when you are aiming the sensors. I have to setup another board to do a long term test with the HK firmware, but I can definitely say that the esp home firmware has been extremely reliable. On Dec 19, 2024, at 7:48 PM, David Kerr ***@***.***> wrote:﻿
Currently parking assist laser is coded to come on for 60 seconds when arriving vehicle arrives.
However, I am finding that the vehicle presence (and therefor arrival/departure) sensing is very inconsistent.
So, should we add a light switch accessory to HomeKit (and a button on the device web page) to allow manual control of the laser... and of course, inclusion in HomeKit automations?

**Comment by dkerr64** [comment]
Added in PR #24

**Comment by dkerr64** [comment]
PR #24 is merged, ability to enable/disable added to PR #26
